- hosts: localhost
  become: yes
  roles:
    - localhost
    - cloud_init
    - libvirt
  
  tasks:
  - name: Whaiting nodes start-uup
    pause:
      seconds: 300 

- hosts: ubuntu
  become: yes
  roles:
    - docker
    - wordpress
 
- hosts: localhost
  become: yes
  roles:
    - haproxy
