- hosts: localhost
  become: true
  vars_prompt:
     - name: ireallymeanit
       prompt: Are you sure you want to destroy the vms?
       defaut: 'yes'
       private: no
  tasks:
    - name: exit playbook, if user did not mean to destroy the vms
      fail:
        msg: >
         "Exiting destroy playbook, vms was NOT destroyed.
          To destroy vms, either say 'yes' on the prompt or
          or use `-e ireallymeanit=yes` on the command line when
          invoking the playbook"
      when: ireallymeanit != 'yes'
     
    - name: Destroy network external
      virt_net:
        command: destroy
        name: external

    - name: Undefine network external
      virt_net:
        command: undefine
        name: external

    - name: Destroy network interna;
      virt_net:
        command: destroy
        name: internal

    - name: Undefine network internal
      virt_net:
        command: undefine
        name: internal

    - name: Check current virtual machines
      virt:
        command: list_vms
      register: vms

    - name: Undefine vms
      virt:
        name: "{{ item.name }}"
        command: undefine
      loop: "{{ virtual_machines }}"
      when: item.name in vms.list_vms

    - name: Destroy vms
      virt:
        name: "{{ item.name }}"
        command: destroy
      loop: "{{ virtual_machines }}"
      when: item.name in vms.list_vms

    - name: Remove vms directories
      file:
        path: /virt/images/iso/{{ item.name }}
        state: absent
      loop: "{{ virtual_machines }}"

