---
cloudimg_url: 

domain: local.lab
# Kvm session
libvirt_dir: /virt

# Vm session: 
enableroot: yes
vm_public_key: "{{lookup('file','~/.ssh/id_rsa.pub')}}"
virtual_machines:
  - name: kvm0
    hostname: ubuntu0
    id: 0
    cpu: 1
    mem: 1024
    disk: 8G
    bridge: virbr0
    net:
      ip: 192.168.124.101
      mask: 255.255.255.0
      dns: 8.8.8.8
  - name: kvm1
    hostname: ubuntu1
    id: 1
    cpu: 1
    mem: 1024
    disk: 8G
    bridge: virbr0
    net:
      ip: 192.168.124.102
      mask: 255.255.255.0
      dns: 8.8.8.8

