---
- name: Network directory 
  file: 
    state: directory 
    path: /virt/network
    mode: 0755

- name: Define external network
  virt_net:
    command: define
    name: external
    xml: '{{ lookup("template", "external.xml.j2") }}'

- name: Define internal network
  virt_net:
    command: define
    name: internal
    xml: '{{ lookup("template", "internal.xml.j2") }}'

- name: Start external network
  virt_net:
    command: start
    name: external

- name: Start internal network
  virt_net:
    command: start
    name: internal

- name: Update network
  virt_net:
    name: external
    command: modify
    xml: "<host mac='{{ vm.mac }}' name='{{ vm.name }}' ip='{{ vm.net.ip }}'/>"

- name: "{{ vm.name }} :: check current virtual machines"
  virt:
    command: list_vms
  register: vms
- name: " Create virtual machines "
  shell: 
    cmd: >- 
        virt-install 
        --noautoconsole
        --name {{ vm.name }}
        --memory {{ vm.mem|default('512') }}
        --vcpus  {{ vm.cpu|default('1') }}
        --disk /virt/images/iso/{{ vm.name }}/{{ vm.name }}.qcow2,device=disk,bus=virtio 
        --disk /virt/images/iso/{{ vm.name }}/cidata.iso,device=cdrom
        --network network=external,mac={{ vm.mac }}
        --network network=internal
        --os-type linux 
        --virt-type kvm 
        --graphics none 
        --import
  when: vm.name not in vms.list_vms      
