---
- name: Install recommended package 
  apt:
    name: "linux-image-extra-virtual"
    update_cache: yes
    install_recommends: no
    state: present

- name: Add official Docker GPG key
  apt_key:
    id: 0EBFCD88
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add official Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: 'docker-official'
    update_cache: yes    

- name: Install docker-compose 
  apt: 
    name: 
    - docker-ce
    - docker-compose 

- name: Add users to the Docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
